/**
 * AUTO-GENERATED COMPONENT REGISTRY
 * ------------------------------
 * DO NOT EDIT DIRECTLY!
 * 
 * This file is automatically generated by build-registry.mts
 * To update, run: npm run build:registry
 * 
 * Total components: 114
 * - Components: 98
 * - Views: 16
 */

export type RegistryItem = {
  name: string
  filePath: string
  type: "view" | "component"
  title?: string
  description?: string
  iframeHeight?: number
}

export const viewRegistry: Record<string, RegistryItem> = {
  "accordion-active": {
    "name": "accordion-active",
    "filePath": "/public/components/accordion/accordion-active.html",
    "type": "component"
  },
  "accordion-structure": {
    "name": "accordion-structure",
    "filePath": "/public/components/accordion/accordion-structure.html",
    "type": "component"
  },
  "accordion": {
    "name": "accordion",
    "filePath": "/public/components/accordion/accordion.html",
    "type": "component"
  },
  "alert-danger": {
    "name": "alert-danger",
    "filePath": "/public/components/alert/alert-danger.html",
    "type": "component"
  },
  "alert-icon-description": {
    "name": "alert-icon-description",
    "filePath": "/public/components/alert/alert-icon-description.html",
    "type": "component"
  },
  "alert-icon-title": {
    "name": "alert-icon-title",
    "filePath": "/public/components/alert/alert-icon-title.html",
    "type": "component"
  },
  "alert-structure": {
    "name": "alert-structure",
    "filePath": "/public/components/alert/alert-structure.html",
    "type": "component"
  },
  "alert-with-description": {
    "name": "alert-with-description",
    "filePath": "/public/components/alert/alert-with-description.html",
    "type": "component"
  },
  "alert-with-title": {
    "name": "alert-with-title",
    "filePath": "/public/components/alert/alert-with-title.html",
    "type": "component"
  },
  "alert": {
    "name": "alert",
    "filePath": "/public/components/alert/alert.html",
    "type": "component"
  },
  "alert-dialog-description": {
    "name": "alert-dialog-description",
    "filePath": "/public/components/alert-dialog/alert-dialog-description.html",
    "type": "component"
  },
  "alert-dialog-footer": {
    "name": "alert-dialog-footer",
    "filePath": "/public/components/alert-dialog/alert-dialog-footer.html",
    "type": "component"
  },
  "alert-dialog-structure": {
    "name": "alert-dialog-structure",
    "filePath": "/public/components/alert-dialog/alert-dialog-structure.html",
    "type": "component"
  },
  "alert-dialog-title": {
    "name": "alert-dialog-title",
    "filePath": "/public/components/alert-dialog/alert-dialog-title.html",
    "type": "component"
  },
  "alert-dialog": {
    "name": "alert-dialog",
    "filePath": "/public/components/alert-dialog/alert-dialog.html",
    "type": "component"
  },
  "avatar-fallback-sizes": {
    "name": "avatar-fallback-sizes",
    "filePath": "/public/components/avatar/avatar-fallback-sizes.html",
    "type": "component"
  },
  "avatar-fallback": {
    "name": "avatar-fallback",
    "filePath": "/public/components/avatar/avatar-fallback.html",
    "type": "component"
  },
  "avatar-group": {
    "name": "avatar-group",
    "filePath": "/public/components/avatar/avatar-group.html",
    "type": "component"
  },
  "avatar-sizes": {
    "name": "avatar-sizes",
    "filePath": "/public/components/avatar/avatar-sizes.html",
    "type": "component"
  },
  "avatar-structure": {
    "name": "avatar-structure",
    "filePath": "/public/components/avatar/avatar-structure.html",
    "type": "component"
  },
  "avatar": {
    "name": "avatar",
    "filePath": "/public/components/avatar/avatar.html",
    "type": "component"
  },
  "badge-colors": {
    "name": "badge-colors",
    "filePath": "/public/components/badge/badge-colors.html",
    "type": "component"
  },
  "badge-ghost": {
    "name": "badge-ghost",
    "filePath": "/public/components/badge/badge-ghost.html",
    "type": "component"
  },
  "badge-outlined": {
    "name": "badge-outlined",
    "filePath": "/public/components/badge/badge-outlined.html",
    "type": "component"
  },
  "badge-radius": {
    "name": "badge-radius",
    "filePath": "/public/components/badge/badge-radius.html",
    "type": "component"
  },
  "badge-sizes": {
    "name": "badge-sizes",
    "filePath": "/public/components/badge/badge-sizes.html",
    "type": "component"
  },
  "badge": {
    "name": "badge",
    "filePath": "/public/components/badge/badge.html",
    "type": "component"
  },
  "breadcrumb-items": {
    "name": "breadcrumb-items",
    "filePath": "/public/components/breadcrumb/breadcrumb-items.html",
    "type": "component"
  },
  "breadcrumb-structure": {
    "name": "breadcrumb-structure",
    "filePath": "/public/components/breadcrumb/breadcrumb-structure.html",
    "type": "component"
  },
  "breadcrumb": {
    "name": "breadcrumb",
    "filePath": "/public/components/breadcrumb/breadcrumb.html",
    "type": "component"
  },
  "button-colors": {
    "name": "button-colors",
    "filePath": "/public/components/button/button-colors.html",
    "type": "component"
  },
  "button-ghost": {
    "name": "button-ghost",
    "filePath": "/public/components/button/button-ghost.html",
    "type": "component"
  },
  "button-icon-only": {
    "name": "button-icon-only",
    "filePath": "/public/components/button/button-icon-only.html",
    "type": "component"
  },
  "button-outline": {
    "name": "button-outline",
    "filePath": "/public/components/button/button-outline.html",
    "type": "component"
  },
  "button-radius": {
    "name": "button-radius",
    "filePath": "/public/components/button/button-radius.html",
    "type": "component"
  },
  "button-sizes": {
    "name": "button-sizes",
    "filePath": "/public/components/button/button-sizes.html",
    "type": "component"
  },
  "button-subtle": {
    "name": "button-subtle",
    "filePath": "/public/components/button/button-subtle.html",
    "type": "component"
  },
  "button": {
    "name": "button",
    "filePath": "/public/components/button/button.html",
    "type": "component"
  },
  "calendar-structure": {
    "name": "calendar-structure",
    "filePath": "/public/components/calendar/calendar-structure.html",
    "type": "component"
  },
  "calendar": {
    "name": "calendar",
    "filePath": "/public/components/calendar/calendar.html",
    "type": "component"
  },
  "card-stats-2": {
    "name": "card-stats-2",
    "filePath": "/public/components/card/card-stats-2.html",
    "type": "component"
  },
  "card-stats": {
    "name": "card-stats",
    "filePath": "/public/components/card/card-stats.html",
    "type": "component"
  },
  "card-structure": {
    "name": "card-structure",
    "filePath": "/public/components/card/card-structure.html",
    "type": "component"
  },
  "card-users": {
    "name": "card-users",
    "filePath": "/public/components/card/card-users.html",
    "type": "component"
  },
  "card": {
    "name": "card",
    "filePath": "/public/components/card/card.html",
    "type": "component"
  },
  "product-card": {
    "name": "product-card",
    "filePath": "/public/components/card/product-card.html",
    "type": "component"
  },
  "checkbox-structure": {
    "name": "checkbox-structure",
    "filePath": "/public/components/checkbox/checkbox-structure.html",
    "type": "component"
  },
  "checkbox-with-indeterminate": {
    "name": "checkbox-with-indeterminate",
    "filePath": "/public/components/checkbox/checkbox-with-indeterminate.html",
    "type": "component"
  },
  "checkbox": {
    "name": "checkbox",
    "filePath": "/public/components/checkbox/checkbox.html",
    "type": "component"
  },
  "combo-box-structure": {
    "name": "combo-box-structure",
    "filePath": "/public/components/combo-box/combo-box-structure.html",
    "type": "component"
  },
  "combo-box": {
    "name": "combo-box",
    "filePath": "/public/components/combo-box/combo-box.html",
    "type": "component"
  },
  "date-picker-range-structure": {
    "name": "date-picker-range-structure",
    "filePath": "/public/components/date-picker/date-picker-range-structure.html",
    "type": "component"
  },
  "date-picker-range": {
    "name": "date-picker-range",
    "filePath": "/public/components/date-picker/date-picker-range.html",
    "type": "component"
  },
  "date-picker": {
    "name": "date-picker",
    "filePath": "/public/components/date-picker/date-picker.html",
    "type": "component"
  },
  "dropdown-menu-checkbox": {
    "name": "dropdown-menu-checkbox",
    "filePath": "/public/components/dropdown-menu/dropdown-menu-checkbox.html",
    "type": "component"
  },
  "dropdown-menu-icons": {
    "name": "dropdown-menu-icons",
    "filePath": "/public/components/dropdown-menu/dropdown-menu-icons.html",
    "type": "component"
  },
  "dropdown-menu-radio": {
    "name": "dropdown-menu-radio",
    "filePath": "/public/components/dropdown-menu/dropdown-menu-radio.html",
    "type": "component"
  },
  "dropdown-menu-structure": {
    "name": "dropdown-menu-structure",
    "filePath": "/public/components/dropdown-menu/dropdown-menu-structure.html",
    "type": "component"
  },
  "dropdown-menu-sub": {
    "name": "dropdown-menu-sub",
    "filePath": "/public/components/dropdown-menu/dropdown-menu-sub.html",
    "type": "component"
  },
  "dropdown-menu": {
    "name": "dropdown-menu",
    "filePath": "/public/components/dropdown-menu/dropdown-menu.html",
    "type": "component"
  },
  "input-both-icon": {
    "name": "input-both-icon",
    "filePath": "/public/components/input/input-both-icon.html",
    "type": "component"
  },
  "input-floating-both-icon": {
    "name": "input-floating-both-icon",
    "filePath": "/public/components/input/input-floating-both-icon.html",
    "type": "component"
  },
  "input-floating-label": {
    "name": "input-floating-label",
    "filePath": "/public/components/input/input-floating-label.html",
    "type": "component"
  },
  "input-floating-left-icon": {
    "name": "input-floating-left-icon",
    "filePath": "/public/components/input/input-floating-left-icon.html",
    "type": "component"
  },
  "input-floating-right-icon": {
    "name": "input-floating-right-icon",
    "filePath": "/public/components/input/input-floating-right-icon.html",
    "type": "component"
  },
  "input-left-icon": {
    "name": "input-left-icon",
    "filePath": "/public/components/input/input-left-icon.html",
    "type": "component"
  },
  "input-right-icon": {
    "name": "input-right-icon",
    "filePath": "/public/components/input/input-right-icon.html",
    "type": "component"
  },
  "input-structure": {
    "name": "input-structure",
    "filePath": "/public/components/input/input-structure.html",
    "type": "component"
  },
  "input-validation": {
    "name": "input-validation",
    "filePath": "/public/components/input/input-validation.html",
    "type": "component"
  },
  "input": {
    "name": "input",
    "filePath": "/public/components/input/input.html",
    "type": "component"
  },
  "list-active": {
    "name": "list-active",
    "filePath": "/public/components/list/list-active.html",
    "type": "component"
  },
  "list-button-icon": {
    "name": "list-button-icon",
    "filePath": "/public/components/list/list-button-icon.html",
    "type": "component"
  },
  "list-structure": {
    "name": "list-structure",
    "filePath": "/public/components/list/list-structure.html",
    "type": "component"
  },
  "list": {
    "name": "list",
    "filePath": "/public/components/list/list.html",
    "type": "component"
  },
  "pagination-structure": {
    "name": "pagination-structure",
    "filePath": "/public/components/pagination/pagination-structure.html",
    "type": "component"
  },
  "pagination": {
    "name": "pagination",
    "filePath": "/public/components/pagination/pagination.html",
    "type": "component"
  },
  "progress-bar-structure": {
    "name": "progress-bar-structure",
    "filePath": "/public/components/progress-bar/progress-bar-structure.html",
    "type": "component"
  },
  "progress-bar": {
    "name": "progress-bar",
    "filePath": "/public/components/progress-bar/progress-bar.html",
    "type": "component"
  },
  "radio-group-structure": {
    "name": "radio-group-structure",
    "filePath": "/public/components/radio-group/radio-group-structure.html",
    "type": "component"
  },
  "radio-group": {
    "name": "radio-group",
    "filePath": "/public/components/radio-group/radio-group.html",
    "type": "component"
  },
  "separator-structure": {
    "name": "separator-structure",
    "filePath": "/public/components/separator/separator-structure.html",
    "type": "component"
  },
  "separator": {
    "name": "separator",
    "filePath": "/public/components/separator/separator.html",
    "type": "component"
  },
  "stepper-active": {
    "name": "stepper-active",
    "filePath": "/public/components/stepper/stepper-active.html",
    "type": "component"
  },
  "stepper-structure": {
    "name": "stepper-structure",
    "filePath": "/public/components/stepper/stepper-structure.html",
    "type": "component"
  },
  "stepper": {
    "name": "stepper",
    "filePath": "/public/components/stepper/stepper.html",
    "type": "component"
  },
  "strength-indicator-danger": {
    "name": "strength-indicator-danger",
    "filePath": "/public/components/strength-indicator/strength-indicator-danger.html",
    "type": "component"
  },
  "strength-indicator-structure": {
    "name": "strength-indicator-structure",
    "filePath": "/public/components/strength-indicator/strength-indicator-structure.html",
    "type": "component"
  },
  "strength-indicator-success": {
    "name": "strength-indicator-success",
    "filePath": "/public/components/strength-indicator/strength-indicator-success.html",
    "type": "component"
  },
  "strength-indicator-warning": {
    "name": "strength-indicator-warning",
    "filePath": "/public/components/strength-indicator/strength-indicator-warning.html",
    "type": "component"
  },
  "strength-indicator": {
    "name": "strength-indicator",
    "filePath": "/public/components/strength-indicator/strength-indicator.html",
    "type": "component"
  },
  "switch": {
    "name": "switch",
    "filePath": "/public/components/switch/switch.html",
    "type": "component"
  },
  "tab-bar-structure": {
    "name": "tab-bar-structure",
    "filePath": "/public/components/tab-bar/tab-bar-structure.html",
    "type": "component"
  },
  "tab-bar": {
    "name": "tab-bar",
    "filePath": "/public/components/tab-bar/tab-bar.html",
    "type": "component"
  },
  "table-customer": {
    "name": "table-customer",
    "filePath": "/public/components/table/table-customer.html",
    "type": "component"
  },
  "table-stripped": {
    "name": "table-stripped",
    "filePath": "/public/components/table/table-stripped.html",
    "type": "component"
  },
  "table-structure": {
    "name": "table-structure",
    "filePath": "/public/components/table/table-structure.html",
    "type": "component"
  },
  "table": {
    "name": "table",
    "filePath": "/public/components/table/table.html",
    "type": "component"
  },
  "textarea": {
    "name": "textarea",
    "filePath": "/public/components/textarea/textarea.html",
    "type": "component"
  },
  "drawer-bottom": {
    "name": "drawer-bottom",
    "filePath": "/public/view/blocks/drawer-bottom.html",
    "type": "view",
    "title": "Bottom Drawer",
    "description": "A panel that slides in from the bottom side of the screen, showing menu items or content without leaving the current page.",
    "iframeHeight": 740
  },
  "drawer-form": {
    "name": "drawer-form",
    "filePath": "/public/view/blocks/drawer-form.html",
    "type": "view",
    "title": "Form Drawer",
    "description": "A sliding panel containing a form for data entry or editing without navigating away from the current context.",
    "iframeHeight": 740
  },
  "drawer-left": {
    "name": "drawer-left",
    "filePath": "/public/view/blocks/drawer-left.html",
    "type": "view",
    "title": "Left Drawer",
    "description": "A panel that slides in from the left side of the screen, showing menu items or content without leaving the current page.",
    "iframeHeight": 740
  },
  "drawer-right": {
    "name": "drawer-right",
    "filePath": "/public/view/blocks/drawer-right.html",
    "type": "view",
    "title": "Right Drawer",
    "description": "A panel that slides in from the right side of the screen, showing menu items or content without leaving the current page.",
    "iframeHeight": 740
  },
  "drawer-top": {
    "name": "drawer-top",
    "filePath": "/public/view/blocks/drawer-top.html",
    "type": "view",
    "title": "Top Drawer",
    "description": "A panel that slides in from the top side of the screen, showing menu items or content without leaving the current page.",
    "iframeHeight": 740
  },
  "drawer-without-overlay": {
    "name": "drawer-without-overlay",
    "filePath": "/public/view/blocks/drawer-without-overlay.html",
    "type": "view",
    "title": "Drawer Without Overlay",
    "description": "A panel that slides in from the side without dimming the background, allowing interaction with the main content.",
    "iframeHeight": 740
  },
  "gantt-chart": {
    "name": "gantt-chart",
    "filePath": "/public/view/blocks/gantt-chart.html",
    "type": "view",
    "title": "Gantt Chart",
    "description": "A project management tool that visualizes tasks and resources over time.",
    "iframeHeight": 740
  },
  "kanban": {
    "name": "kanban",
    "filePath": "/public/view/blocks/kanban.html",
    "type": "view",
    "title": "",
    "description": "",
    "iframeHeight": 740
  },
  "screen-state": {
    "name": "screen-state",
    "filePath": "/public/view/blocks/screen-state.html",
    "type": "view",
    "title": "Screen State",
    "description": "Component for displaying different UI states like loading, empty, or error conditions.",
    "iframeHeight": 480
  },
  "dashboard-layout-01": {
    "name": "dashboard-layout-01",
    "filePath": "/public/view/layouts/dashboard-layout-01.html",
    "type": "view",
    "title": "Dashboard Layout",
    "description": "A responsive dashboard layout with sidebar and header navigation.",
    "iframeHeight": 740
  },
  "dashboard-layout-02": {
    "name": "dashboard-layout-02",
    "filePath": "/public/view/layouts/dashboard-layout-02.html",
    "type": "view",
    "title": "Dashboard Layout",
    "description": "A responsive dashboard layout with sidebar and header navigation",
    "iframeHeight": 740
  },
  "header-01": {
    "name": "header-01",
    "filePath": "/public/view/layouts/header-01.html",
    "type": "view",
    "title": "Header",
    "description": "Navigation header at the top of the UI that provides access to key sections and features.",
    "iframeHeight": 740
  },
  "sidebar-01": {
    "name": "sidebar-01",
    "filePath": "/public/view/layouts/sidebar-01.html",
    "type": "view",
    "title": "Sidebar",
    "description": "Vertical navigation panel for site or app sections, typically positioned at the side of the screen.",
    "iframeHeight": 740
  },
  "sidebar-02": {
    "name": "sidebar-02",
    "filePath": "/public/view/layouts/sidebar-02.html",
    "type": "view",
    "title": "Sidebar without icons",
    "description": "Vertical navigation panel with text-only links, providing a clean and minimal side navigation experience.",
    "iframeHeight": 740
  },
  "sidebar-03": {
    "name": "sidebar-03",
    "filePath": "/public/view/layouts/sidebar-03.html",
    "type": "view",
    "title": "Sidebar with Dropdown Items",
    "description": "Expandable sidebar navigation with dropdown menus for organizing content into hierarchical categories.",
    "iframeHeight": 740
  },
  "sidebar-04": {
    "name": "sidebar-04",
    "filePath": "/public/view/layouts/sidebar-04.html",
    "type": "view",
    "title": "Double Sidebar",
    "description": "Two-level sidebar layout with primary and secondary navigation panels for complex application structures.",
    "iframeHeight": 740
  }
};
