import {
	readdirSync,
	readFileSync,
	writeFileSync,
	mkdirSync,
	existsSync,
} from "fs";
import { join, relative } from "path";

const COMPONENTS_DIR = "./components";
const OUTPUT_DIR = "./previews";
const MAIN_INDEX = "./index.html";

const OUTPUT_CSS_PATH = "../css/output.css";

type ComponentNode =
	| {
			name: string;
			type: "folder";
			children: ComponentNode[];
			path: string;
	  }
	| {
			name: string;
			type: "file";
			path: string;
	  };

function walkComponents(dir: string = COMPONENTS_DIR): ComponentNode[] {
	const entries = readdirSync(dir, { withFileTypes: true });
	const result: ComponentNode[] = [];

	for (const entry of entries) {
		const fullPath = join(dir, entry.name);

		if (entry.isDirectory()) {
			result.push({
				name: entry.name,
				type: "folder",
				children: walkComponents(fullPath),
				path: fullPath,
			});
		} else if (entry.isFile() && entry.name.endsWith(".html")) {
			result.push({
				name: entry.name,
				type: "file",
				path: relative(".", fullPath),
			});
		}
	}

	return result;
}

function generateComponentPreview(folderNode: ComponentNode): string {
	if (folderNode.type !== "folder") return "";

	const components = folderNode.children.filter(
		(child) => child.type === "file",
	);

	const componentCards = components
		.map((component) => {
			if (component.type !== "file") return "";

			const content = readFileSync(component.path, "utf8").trim();
			const componentName = component.name.replace(".html", "");

			return `
    <div class="bg-white rounded-lg shadow-md overflow-hidden border border-gray-200">
      <div class="bg-gray-50 px-6 py-3 border-b border-gray-200">
        <h3 class="text-lg font-semibold text-gray-800">${componentName}</h3>
      </div>
      <div class="p-8 bg-white">
        <div class="flex items-center justify-center min-h-[120px] bg-gray-50 rounded-lg p-6">
          ${content}
        </div>
      </div>
    </div>
  `;
		})
		.join("\n");

	return `<!-- 
  THIS FILE IS AUTOGENERATED. DO NOT EDIT IT MANUALLY.
-->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${folderNode.name.charAt(0).toUpperCase() + folderNode.name.slice(1)} Components</title>
  <link href="${OUTPUT_CSS_PATH}" rel="stylesheet">
  <style>
    .component-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(400px, 1fr));
      gap: 2rem;
    }
    @media (max-width: 768px) {
      .component-grid {
        grid-template-columns: 1fr;
      }
    }
  </style>
</head>
<body class="bg-gray-100 min-h-screen">
  <div class="container mx-auto px-6 py-8">
    <div class="mb-8">
      <nav class="mb-4">
        <a href="../index.html" class="text-blue-600 hover:text-blue-800 font-medium">← Back to All Components</a>
      </nav>
      <h1 class="text-4xl font-bold text-gray-900 mb-2">${folderNode.name.charAt(0).toUpperCase() + folderNode.name.slice(1)} Components</h1>
      <p class="text-gray-600">Preview of all ${folderNode.name} component variations</p>
    </div>
    
    <div class="component-grid">
      ${componentCards}
    </div>
  </div>
</body>
</html>`;
}

function generateMainIndex(tree: ComponentNode[]): string {
	const folders = tree.filter((node) => node.type === "folder");

	const folderCards = folders
		.map((folder) => {
			if (folder.type !== "folder") return "";

			const componentCount = folder.children.filter(
				(child) => child.type === "file",
			).length;
			const previewFileName = `${folder.name}-preview.html`;

			return `
      <a href="previews/${previewFileName}" class="block group">
        <div class="bg-white rounded-lg shadow-md hover:shadow-lg transition-shadow duration-200 border border-gray-200 overflow-hidden">
          <div class="p-6">
            <div class="flex items-center justify-between mb-4">
              <h3 class="text-xl font-semibold text-gray-900 group-hover:text-blue-600 transition-colors">
                ${folder.name.charAt(0).toUpperCase() + folder.name.slice(1)}
              </h3>
              <span class="bg-blue-100 text-blue-800 text-sm font-medium px-2.5 py-0.5 rounded-full">
                ${componentCount} components
              </span>
            </div>
            <p class="text-gray-600 mb-4">
              View all ${folder.name} component variations and examples
            </p>
            <div class="flex items-center text-blue-600 group-hover:text-blue-800 font-medium">
              View Components
              <svg class="w-4 h-4 ml-2 group-hover:translate-x-1 transition-transform" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path>
              </svg>
            </div>
          </div>
        </div>
      </a>
    `;
		})
		.join("\n");

	return `<!-- 
  THIS FILE IS AUTOGENERATED. DO NOT EDIT IT MANUALLY.
-->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>MijnUI Tailwind Components</title>
  <link href="css/output.css" rel="stylesheet">
  <style>
    .component-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
      gap: 1.5rem;
    }
    @media (max-width: 768px) {
      .component-grid {
        grid-template-columns: 1fr;
      }
    }
  </style>
</head>
<body class="bg-gray-100 min-h-screen">
  <div class="container mx-auto px-6 py-8">
    <div class="text-center mb-12">
      <h1 class="text-5xl font-bold text-gray-900 mb-4">Tailwind Component Library</h1>
      <p class="text-xl text-gray-600 max-w-2xl mx-auto">
        A comprehensive collection of reusable Tailwind CSS components. Click on any category to explore the available components.
      </p>
    </div>
    
    <div class="mb-8">
      <div class="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
        <div class="grid grid-cols-1 md:grid-cols-3 gap-4 text-center">
          <div>
            <div class="text-3xl font-bold text-blue-600">${folders.length}</div>
            <div class="text-gray-600">Component Categories</div>
          </div>
          <div>
            <div class="text-3xl font-bold text-green-600">${folders.reduce((total, folder) => total + (folder.type === "folder" ? folder.children.filter((child) => child.type === "file").length : 0), 0)}</div>
            <div class="text-gray-600">Total Components</div>
          </div>
          <div>
            <div class="text-3xl font-bold text-purple-600">100%</div>
            <div class="text-gray-600">Tailwind CSS</div>
          </div>
        </div>
      </div>
    </div>
    
    <div class="component-grid">
      ${folderCards}
    </div>
    
    <div class="mt-12 text-center">
      <p class="text-gray-500">
        Built with ❤️ using by Htet Aung Lin
      </p>
    </div>
  </div>
</body>
</html>`;
}

// Create output directory if it doesn't exist
if (!existsSync(OUTPUT_DIR)) {
	mkdirSync(OUTPUT_DIR, { recursive: true });
}

// Generate component tree
console.log("🔄 Generating component previews...");
const tree = walkComponents();

// Generate individual preview files for each folder
const folders = tree.filter((node) => node.type === "folder");
folders.forEach((folder) => {
	if (folder.type === "folder") {
		const previewHTML = generateComponentPreview(folder);
		const fileName = `${folder.name}-preview.html`;
		writeFileSync(join(OUTPUT_DIR, fileName), previewHTML);
		console.log(`✅ Generated ${fileName}`);
	}
});

// Generate main index file
const mainIndexHTML = generateMainIndex(tree);
writeFileSync(MAIN_INDEX, mainIndexHTML);

console.log(`✅ Generated main index.html`);
console.log(`✅ Total preview files created: ${folders.length}`);
console.log(`🎉 Component preview system ready!`);
